# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-25 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_description', models.CharField(max_length=200)),
                ('asset_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/temp')),
                ('asset_image_thumbnail', models.ImageField(editable=False, null=True, upload_to='images')),
                ('asset_details', models.TextField(blank=True)),
                ('asset_manufacturer', models.CharField(blank=True, max_length=255)),
                ('asset_model', models.CharField(blank=True, max_length=255)),
                ('asset_serial_number', models.CharField(blank=True, max_length=255)),
                ('asset_handling_and_storage_instructions', models.URLField(blank=True, max_length=255, null=True)),
                ('asset_operating_instructions', models.URLField(blank=True, max_length=255, null=True)),
                ('person_responsible', models.CharField(max_length=100)),
                ('person_responsible_email', models.EmailField(max_length=254)),
                ('requires_insurance', models.BooleanField()),
                ('requires_safety_checks', models.BooleanField()),
                ('requires_environmental_checks', models.BooleanField()),
                ('requires_planned_maintenance', models.BooleanField()),
                ('maintenance_instructions', models.URLField(blank=True, max_length=255, null=True)),
                ('maintenance_records', models.URLField(blank=True, max_length=255, null=True)),
                ('requires_calibration', models.BooleanField()),
                ('passed_calibration', models.BooleanField(default=False)),
                ('calibration_date_prev', models.DateField(blank=True, null=True)),
                ('calibration_date_next', models.DateField(blank=True, null=True)),
                ('calibration_instructions', models.URLField(blank=True, max_length=255, null=True)),
                ('asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_order_ref', models.CharField(blank=True, max_length=15)),
                ('funded_by', models.CharField(blank=True, max_length=255)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('asset_location_room', models.CharField(blank=True, max_length=255)),
                ('edited_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
                ('EFM_building_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('calibration_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('calibration_description', models.CharField(max_length=200)),
                ('calibration_date', models.DateField(default=django.utils.timezone.now)),
                ('calibration_date_next', models.DateField(blank=True, null=True)),
                ('calibrated_by_external', models.CharField(blank=True, max_length=200, null=True)),
                ('calibration_outcome', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='Pass', max_length=10)),
                ('calibration_notes', models.TextField(blank=True, null=True)),
                ('calibration_certificate', models.URLField(blank=True, max_length=255, null=True)),
                ('calibration_entered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='assetregister.Asset')),
                ('calibrated_by_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibrator', to=settings.AUTH_USER_MODEL)),
                ('calibration_entered_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calibration_entered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_location_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building', to='assetregister.Buildings'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='assetregister.AssetStatus'),
        ),
        migrations.AddField(
            model_name='asset',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_assets',
            field=models.ManyToManyField(blank=True, related_name='_asset_parent_assets_+', to='assetregister.Asset'),
        ),
    ]
