# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-08 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_description', models.CharField(max_length=200)),
                ('asset_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/temp')),
                ('asset_image_thumbnail', models.ImageField(editable=False, null=True, upload_to='images')),
                ('asset_details', models.TextField(blank=True)),
                ('asset_manufacturer', models.CharField(blank=True, max_length=255)),
                ('asset_model', models.CharField(blank=True, max_length=255)),
                ('asset_serial_number', models.CharField(blank=True, max_length=255)),
                ('asset_status', models.CharField(choices=[('Active / In-Use', 'Active / In-Use'), ('Inactive (Being Comissioned / Repaired)', 'Inactive (Being Comissioned / Repaired)'), ('Quarantined', 'Quarantined'), ('Decomissioned / Withdrawn', 'Decomissioned / Withdrawn'), ('Archived', 'Archived')], default='Active / In-Use', max_length=100)),
                ('person_responsible', models.CharField(max_length=100)),
                ('person_responsible_email', models.EmailField(max_length=254)),
                ('requires_insurance', models.BooleanField()),
                ('requires_safety_checks', models.BooleanField()),
                ('requires_environmental_checks', models.BooleanField()),
                ('requires_planned_maintenance', models.BooleanField()),
                ('maintenance_instructions', models.URLField(blank=True, max_length=255, null=True)),
                ('requires_calibration', models.BooleanField()),
                ('calibration_date_prev', models.DateField(blank=True, null=True)),
                ('calibration_date_next', models.DateField(blank=True, null=True)),
                ('calibration_instructions', models.URLField(blank=True, max_length=255, null=True)),
                ('asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_order_ref', models.CharField(blank=True, max_length=15)),
                ('funded_by', models.CharField(blank=True, max_length=255)),
                ('acquired_on', models.DateTimeField(blank=True, null=True)),
                ('asset_location_building', models.CharField(blank=True, choices=[('Rolls-Royce Factory of the Future (8306)', 'Rolls-Royce Factory of the Future (8306)'), ('Factory 2050 (8324)', 'Factory 2050 (8324)'), ('Design, Prototyping & Testing Centre (8304)', 'Design, Prototyping & Testing Centre (8304)'), ('Nuclear AMRC (8307)', 'Nuclear AMRC (8307)'), ('Knowledge Transfer Centre (8313)', 'Knowledge Transfer Centre (8313)'), ('AMRC Training Centre (8320)', 'AMRC Training Centre (8320)'), ('Castings Technology International 1 (Waverly 1) (8322)', 'Castings Technology International 1 (Waverly 1) (8322)'), ('Castings Foundry of the Future (Waverly 2) (8323)', 'Castings Foundry of the Future (Waverly 2) (8323)')], max_length=128)),
                ('asset_location_room', models.CharField(blank=True, max_length=255)),
                ('edited_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_to_other_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetregister.Asset')),
            ],
        ),
    ]
