# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 12:54
from __future__ import unicode_literals

import assetregister.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_description', models.CharField(max_length=200)),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to=assetregister.models.img_path_and_rename)),
                ('asset_details', models.TextField()),
                ('asset_status', models.IntegerField(choices=[('1', 'Active / In-Use'), ('2', 'Inactive (Being Comissioned / Repaired)'), ('3', 'Quarantined'), ('4', 'Decomissioned / Withdrawn')])),
                ('requires_calibration', models.BooleanField()),
                ('requires_safetychecks', models.BooleanField()),
                ('requires_environmentalchecks', models.BooleanField()),
                ('requires_plannedmaintenance', models.BooleanField()),
                ('significant_value', models.BooleanField()),
                ('person_responsible', models.CharField(max_length=100)),
                ('person_responsible_email', models.EmailField(max_length=254)),
                ('acquired_on', models.DateTimeField(null=True)),
                ('purchase_order_ref', models.CharField(max_length=15, null=True)),
                ('funded_by', models.CharField(max_length=200, null=True)),
                ('asset_location_building', models.CharField(choices=[('FOF', 'Rolls-Royce Factory of the Future (8306)'), ('2050', 'Factory 2050 (8324)'), ('DPTC', 'Design, Prototyping & Testing Centre (8304)'), ('NAMRC', 'Nuclear AMRC (8307)'), ('KTC', 'Knowledge Transfer Centre (8313)'), ('TC', 'AMRC Training Centre (8320)'), ('CTI', 'Castings Technology International 1 (Waverly 1) (8322)'), ('WAV2', 'Castings Foundry of the Future (Waverly 2) (8323)')], max_length=5, null=True)),
                ('asset_location_room', models.CharField(max_length=200, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
