# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-25 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_handling_and_storage_instructions',
            new_name='handling_and_storage_instructions',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_operating_instructions',
            new_name='operating_instructions',
        ),
    ]
