# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-01-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_handling_and_storage_instructions',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_operating_instructions',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='calibration_records',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_records',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
