# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-21 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assetregister', '0002_auto_20170105_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('calibration_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('calibration_description', models.CharField(max_length=200)),
                ('calibration_date', models.DateField()),
                ('calibration_date_next', models.DateField(blank=True, null=True)),
                ('calibrated_by_external', models.CharField(blank=True, max_length=200, null=True)),
                ('calibration_pass', models.BooleanField()),
                ('calibration_fail', models.BooleanField()),
                ('calibration_notes', models.TextField(blank=True, null=True)),
                ('calibration_certificate', models.URLField(blank=True, max_length=255, null=True)),
                ('calibration_entered_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='assetregister.Asset'),
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='calibrated_by_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='calibration_entered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calibration_entered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
