# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-14 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0002_auto_20160413_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquired_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_location_building',
            field=models.CharField(blank=True, choices=[('FOF', 'Rolls-Royce Factory of the Future (8306)'), ('2050', 'Factory 2050 (8324)'), ('DPTC', 'Design, Prototyping & Testing Centre (8304)'), ('NAMRC', 'Nuclear AMRC (8307)'), ('KTC', 'Knowledge Transfer Centre (8313)'), ('TC', 'AMRC Training Centre (8320)'), ('CTI', 'Castings Technology International 1 (Waverly 1) (8322)'), ('WAV2', 'Castings Foundry of the Future (Waverly 2) (8323)')], max_length=5),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_location_room',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.IntegerField(choices=[(1, 'Active / In-Use'), (2, 'Inactive (Being Comissioned / Repaired)'), (3, 'Quarantined'), (4, 'Decomissioned / Withdrawn')], default=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='funded_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_order_ref',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
