# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-26 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0003_auto_20170225_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='environmental_notes',
            field=models.TextField(blank=True),
        ),
    ]
