# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0004_asset_environmental_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrecord',
            name='slug',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
