# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-14 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0004_auto_20160414_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='value',
            new_name='asset_value',
        ),
    ]
