# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-14 11:26
from __future__ import unicode_literals

import assetregister.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0005_auto_20160414_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='significant_value',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='calibration_instructions',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=assetregister.models.calibration_instructions_path_and_rename),
        ),
    ]
