# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-28 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0005_calibrationrecord_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrecord',
            name='calibrated_by_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='calibration_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_entered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
