# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-23 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0005_auto_20170223_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='ok_to_use',
            new_name='passed_calibration',
        ),
    ]
