# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-24 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0006_auto_20170223_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='passed_calibration',
            field=models.BooleanField(default=False),
        ),
    ]
