# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-01 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0006_auto_20170228_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrecord',
            name='calibration_entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
