# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0007_auto_20170301_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='amrc_equipment_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
