# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-24 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0007_auto_20170224_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='calibration_records',
        ),
    ]
