# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0008_asset_asset_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='added_by',
            new_name='edited_by',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='added_on',
            new_name='edited_on',
        ),
    ]
