# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-05 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0008_asset_amrc_equipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='disposal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
