# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-06 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0009_asset_disposal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrecord',
            name='slug',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
