# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-13 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0009_auto_20160420_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='calibration_date_next',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='calibration_date_prev',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
