# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0009_auto_20170224_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='related_to_other_asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_assets',
            field=models.ManyToManyField(blank=True, related_name='_asset_parent_assets_+', to='assetregister.Asset'),
        ),
    ]
