# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-06 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0010_auto_20170306_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='amrc_equipment_ID',
            new_name='amrc_equipment_id',
        ),
    ]
