# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0010_auto_20170224_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='acquired_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrecord',
            name='calibration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
