# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0010_auto_20160913_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='calibration_date_next',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='calibration_date_prev',
            field=models.DateField(blank=True, null=True),
        ),
    ]
