# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0012_auto_20170306_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='charge_out_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='safety_notes',
            field=models.TextField(blank=True),
        ),
    ]
