# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-06 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0012_auto_20160913_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/temp'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_location_room',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='calibration_instructions',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='files/calibration_instructions/temp'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='funded_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
