# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0013_auto_20161006_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_location_building',
            field=models.CharField(blank=True, choices=[('Rolls-Royce Factory of the Future (8306)', 'Rolls-Royce Factory of the Future (8306)'), ('Factory 2050 (8324)', 'Factory 2050 (8324)'), ('Design, Prototyping & Testing Centre (8304)', 'Design, Prototyping & Testing Centre (8304)'), ('Nuclear AMRC (8307)', 'Nuclear AMRC (8307)'), ('Knowledge Transfer Centre (8313)', 'Knowledge Transfer Centre (8313)'), ('AMRC Training Centre (8320)', 'AMRC Training Centre (8320)'), ('Castings Technology International 1 (Waverly 1) (8322)', 'Castings Technology International 1 (Waverly 1) (8322)'), ('Castings Foundry of the Future (Waverly 2) (8323)', 'Castings Foundry of the Future (Waverly 2) (8323)')], max_length=128),
        ),
    ]
