# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0015_auto_20161122_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='requires_insurance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
