# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0016_asset_requires_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image_tumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='images/temp/thumbs'),
        ),
    ]
