# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-25 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0017_asset_asset_image_tumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_image_tumbnail',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_image_thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='images'),
        ),
    ]
