# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0017_auto_20170307_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='disposal_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
