# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-08 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0018_asset_disposal_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='charge_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
