# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-08 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0019_asset_charge_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addresses', models.CharField(max_length=255)),
                ('email_for', models.CharField(max_length=16)),
            ],
        ),
    ]
