# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-09 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0020_emailsto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsto',
            old_name='email_addresses',
            new_name='email_address',
        ),
    ]
