# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0021_auto_20170309_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsto',
            name='email_for',
            field=models.CharField(choices=[('Calibrated Asset', 'CALIBRATION'), ('High Value Asset', 'FINANCE'), ('Asset with Environmental Aspect', 'ENVIRO')], max_length=16),
        ),
    ]
