# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0022_auto_20170309_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsto',
            name='email_for',
            field=models.CharField(choices=[('Calibrated Asset', 'Calibrated Asset'), ('High Value Asset', 'High Value Asset'), ('Asset with Environmental Aspect', 'Asset with Environmental Aspect')], max_length=56),
        ),
    ]
