# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0023_auto_20170309_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationAssetNotificaton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalAspectAssetNoficiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='HighValueAssetNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=128)),
                ('if_asset_value_above', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailsTo',
        ),
    ]
