# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-10 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0024_auto_20170310_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnviroAspects',
            new_name='EnvironmentalAspects',
        ),
    ]
