# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0027_userpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='access_calibration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='access_finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='access_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
