# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0028_auto_20170413_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='add_or_edit_assets',
            field=models.BooleanField(default=False),
        ),
    ]
