# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0029_userpermissions_add_or_edit_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
