# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0031_auto_20170427_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='emergency_response_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='environmental_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='maintenance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='safety_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
