# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0032_auto_20170427_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='calibration_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_status', to='assetregister.CalibrationStatus'),
        ),
    ]
