# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0033_auto_20170612_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='calibration_type',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=10, null=True),
        ),
    ]
