# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0035_auto_20171006_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='amrcgroup',
            name='ad_ou_group_mapping',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
