# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0041_asset_dispatch_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='dispatch_note',
            new_name='dispatch_note_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='grn',
            new_name='grn_id',
        ),
    ]
