# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0042_auto_20171017_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_qr_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_qr_location_id', to='assetregister.QRLocation'),
        ),
    ]
