# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetregister', '0043_asset_asset_qr_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_qr_location_id',
            new_name='asset_qr_location',
        ),
    ]
